mv  1/img.pdf                 1/1_img.pdf
mv  1/img.png                 1/1_img.png
mv  1/fil.pdf                 1/1_fil.pdf
mv  1/fil.png                 1/1_fil.png
mv  1/seg.pdf                 1/1_seg.pdf
mv  1/seg.png                 1/1_seg.png
mv  1/dss_z1.pdf              1/1_dss_z1.pdf
mv  1/dss_z1.png              1/1_dss_z1.png
mv  1/dss_z2.pdf              1/1_dss_z2.pdf
mv  1/dss_z2.png              1/1_dss_z2.png
mv  1/*_p.eps                 1/1_p.eps
mv  1/*_p.png                 1/1_p.png
mv  1/*_2mass.pdf             1/1_2mass.pdf
mv  1/*_2mass.png             1/1_2mass.png
mv  1/*_m.pdf                 1/1_m.pdf
mv  1/*_m.png                 1/1_m.png
mv  1/*_sdss.pdf              1/1_sdss.pdf
mv  1/*_sdss.png              1/1_sdss.png
mv  1/*_zg.pdf                1/1_zg.pdf
mv  1/*_zg.png                1/1_zg.png
mv  1/mex.pdf                 1/1_mex.pdf
mv  1/mex.png                 1/1_mex.png
mv  1/nh.pdf                  1/1_nh.pdf
mv  1/nh.png                  1/1_nh.png


mv  2/img.pdf                 2/2_img.pdf
mv  2/img.png                 2/2_img.png
mv  2/fil.pdf                 2/2_fil.pdf
mv  2/fil.png                 2/2_fil.png
mv  2/seg.pdf                 2/2_seg.pdf
mv  2/seg.png                 2/2_seg.png
mv  2/dss_z1.pdf              2/2_dss_z1.pdf
mv  2/dss_z1.png              2/2_dss_z1.png
mv  2/dss_z2.pdf              2/2_dss_z2.pdf
mv  2/dss_z2.png              2/2_dss_z2.png
mv  2/*_p.eps                 2/2_p.eps
mv  2/*_p.png                 2/2_p.png
mv  2/*_2mass.pdf             2/2_2mass.pdf
mv  2/*_2mass.png             2/2_2mass.png
mv  2/*_m.pdf                 2/2_m.pdf
mv  2/*_m.png                 2/2_m.png
mv  2/*_sdss.pdf              2/2_sdss.pdf
mv  2/*_sdss.png              2/2_sdss.png
mv  2/*_zg.pdf                2/2_zg.pdf
mv  2/*_zg.png                2/2_zg.png
mv  2/mex.pdf                 2/2_mex.pdf
mv  2/mex.png                 2/2_mex.png
mv  2/nh.pdf                  2/2_nh.pdf
mv  2/nh.png                  2/2_nh.png


mv  3/img.pdf                 3/3_img.pdf
mv  3/img.png                 3/3_img.png
mv  3/fil.pdf                 3/3_fil.pdf
mv  3/fil.png                 3/3_fil.png
mv  3/seg.pdf                 3/3_seg.pdf
mv  3/seg.png                 3/3_seg.png
mv  3/dss_z1.pdf              3/3_dss_z1.pdf
mv  3/dss_z1.png              3/3_dss_z1.png
mv  3/dss_z2.pdf              3/3_dss_z2.pdf
mv  3/dss_z2.png              3/3_dss_z2.png
mv  3/*_p.eps                 3/3_p.eps
mv  3/*_p.png                 3/3_p.png
mv  3/*_2mass.pdf             3/3_2mass.pdf
mv  3/*_2mass.png             3/3_2mass.png
mv  3/*_m.pdf                 3/3_m.pdf
mv  3/*_m.png                 3/3_m.png
mv  3/*_sdss.pdf              3/3_sdss.pdf
mv  3/*_sdss.png              3/3_sdss.png
mv  3/*_zg.pdf                3/3_zg.pdf
mv  3/*_zg.png                3/3_zg.png
mv  3/mex.pdf                 3/3_mex.pdf
mv  3/mex.png                 3/3_mex.png
mv  3/nh.pdf                  3/3_nh.pdf
mv  3/nh.png                  3/3_nh.png


mv  4/img.pdf                 4/4_img.pdf
mv  4/img.png                 4/4_img.png
mv  4/fil.pdf                 4/4_fil.pdf
mv  4/fil.png                 4/4_fil.png
mv  4/seg.pdf                 4/4_seg.pdf
mv  4/seg.png                 4/4_seg.png
mv  4/dss_z1.pdf              4/4_dss_z1.pdf
mv  4/dss_z1.png              4/4_dss_z1.png
mv  4/dss_z2.pdf              4/4_dss_z2.pdf
mv  4/dss_z2.png              4/4_dss_z2.png
mv  4/*_p.eps                 4/4_p.eps
mv  4/*_p.png                 4/4_p.png
mv  4/*_2mass.pdf             4/4_2mass.pdf
mv  4/*_2mass.png             4/4_2mass.png
mv  4/*_m.pdf                 4/4_m.pdf
mv  4/*_m.png                 4/4_m.png
mv  4/*_sdss.pdf              4/4_sdss.pdf
mv  4/*_sdss.png              4/4_sdss.png
mv  4/*_zg.pdf                4/4_zg.pdf
mv  4/*_zg.png                4/4_zg.png
mv  4/mex.pdf                 4/4_mex.pdf
mv  4/mex.png                 4/4_mex.png
mv  4/nh.pdf                  4/4_nh.pdf
mv  4/nh.png                  4/4_nh.png


mv  5/img.pdf                 5/5_img.pdf
mv  5/img.png                 5/5_img.png
mv  5/fil.pdf                 5/5_fil.pdf
mv  5/fil.png                 5/5_fil.png
mv  5/seg.pdf                 5/5_seg.pdf
mv  5/seg.png                 5/5_seg.png
mv  5/dss_z1.pdf              5/5_dss_z1.pdf
mv  5/dss_z1.png              5/5_dss_z1.png
mv  5/dss_z2.pdf              5/5_dss_z2.pdf
mv  5/dss_z2.png              5/5_dss_z2.png
mv  5/*_p.eps                 5/5_p.eps
mv  5/*_p.png                 5/5_p.png
mv  5/*_2mass.pdf             5/5_2mass.pdf
mv  5/*_2mass.png             5/5_2mass.png
mv  5/*_m.pdf                 5/5_m.pdf
mv  5/*_m.png                 5/5_m.png
mv  5/*_sdss.pdf              5/5_sdss.pdf
mv  5/*_sdss.png              5/5_sdss.png
mv  5/*_zg.pdf                5/5_zg.pdf
mv  5/*_zg.png                5/5_zg.png
mv  5/mex.pdf                 5/5_mex.pdf
mv  5/mex.png                 5/5_mex.png
mv  5/nh.pdf                  5/5_nh.pdf
mv  5/nh.png                  5/5_nh.png


